version: "3"

services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/blog:/src
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    depends_on:
      - app
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile-php7
    ports:
      - 8090:8090
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./src/blog:/src
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./logs:/var/log/php
    # command: Ubiquity serve -h app
  db:
    image: mysql:5.7
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - "./my.cnf:/etc/mysql/conf.d/cyfons.cnf"
      - "${DOCKER_MYSQL_DATA_DIR}:/var/lib/mysql"
      - ./logs:/var/log/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: .env
    environment:
      PMA_HOST: db
    depends_on:
      - db
    ports:
      - 8033:80
    volumes:
      - "phpmyadminSession:/sessions"
  maildev:
    image: kanemu/maildev-with-iconv
    ports:
      - 8025:80
volumes:
  phpmyadminSession:
